package com.gabrielpc.enginesoundsimulator.audio

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.lerp

/**
 * Human-facing facts for the exact Assetto/mod variants packaged by this project.
 *
 * Generated by `tools/generate_car_subtitles.py`; do not hand-edit. Values come from each
 * source car's `ui_car.json` performance specs (HP, 0-100, torque, weight) for the packaged
 * variant, with road-car price bands appended when a market comparison exists.
 */
internal data class CarSubtitle(
    val horsepower: Int?,
    val details: String,
)

internal object CarSubtitleCatalog {
    private val fallback = CarSubtitle(null, "ASSETTO CORSA AUDIO PROFILE")

    private val subtitles = mapOf(
        "alfa-romeo-4c" to CarSubtitle(240, "4,5s · 36 Kgfm · 925 Kg · ~ R$: 250.000–900.000"),
        "assetto-alfa-romeo-giulietta-qv" to CarSubtitle(235, "6,6s · 36 Kgfm · 1390 Kg · ~ R$: 100.000–500.000"),
        "assetto-alfa-romeo-giulietta-qv-le" to CarSubtitle(240, "6s · 36 Kgfm · 1390 Kg · ~ R$: 100.000–500.000"),
        "assetto-audi-r8-lms-2016" to CarSubtitle(500, "3,5s · 51 Kgfm · 1270 Kg · ~ R$: 500.000–900.000"),
        "assetto-audi-r8-plus" to CarSubtitle(550, "3,5s · 55 Kgfm · 1620 Kg · ~ R$: 500.000–900.000"),
        "assetto-audi-tt-cup" to CarSubtitle(310, "4,7s · 1125 Kg"),
        "assetto-bmw-1m-s3" to CarSubtitle(400, "3,8s · 59 Kgfm · 1495 Kg · ~ R$: 100.000–500.000"),
        "assetto-bmw-m3-e92-s1" to CarSubtitle(414, "4,3s · 41 Kgfm · 1605 Kg · ~ R$: 300.000–700.000"),
        "assetto-bmw-m3-gt2" to CarSubtitle(485, "3,3s · 51 Kgfm · 1245 Kg · ~ R$: 300.000–700.000"),
        "assetto-bmw-m4" to CarSubtitle(431, "3,9s · 56 Kgfm · 1572 Kg · ~ R$: 300.000–700.000"),
        "assetto-bmw-z4-gt3" to CarSubtitle(530, "3,3s · 53 Kgfm · 1265 Kg · ~ R$: 300.000–700.000"),
        "assetto-corvette-c7-stingray" to CarSubtitle(455, "3,8s · 64 Kgfm · 1496 Kg · ~ R$: 300.000–700.000"),
        "assetto-ferrari-458-gt2" to CarSubtitle(470, "3,3s · 53 Kgfm · 1245 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-ferrari-458-s3" to CarSubtitle(570, "3,8s · 55 Kgfm · 1140 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-ferrari-488-gt3" to CarSubtitle(500, "3,3s · 65 Kgfm · 1270 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-ferrari-488-gtb" to CarSubtitle(660, "3s · 77 Kgfm · 1370 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-ferrari-599xxevo" to CarSubtitle(750, "2,5s · 71 Kgfm · 1310 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-ferrari-f40" to CarSubtitle(478, "3,5s · 59 Kgfm · 1175 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-ferrari-fxx-k" to CarSubtitle(1050, "3s"),
        "assetto-ferrari-laferrari" to CarSubtitle(963, "3s · ~ R$: 2.000.000–4.000.000"),
        "assetto-ks-alfa-giulia-qv" to CarSubtitle(510, "3,9s · 61 Kgfm · 1595 Kg · ~ R$: 250.000–900.000"),
        "assetto-ks-alfa-mito-qv" to CarSubtitle(168, "7,3s · 25 Kgfm · 1140 Kg · ~ R$: 250.000–900.000"),
        "assetto-ks-audi-a1s1" to CarSubtitle(231, "5,8s · 38 Kgfm · 1340 Kg · ~ R$: 100.000–500.000"),
        "assetto-ks-audi-r18-etron-quattro" to CarSubtitle(700, "3s · 915 Kg · ~ R$: 100.000–500.000"),
        "assetto-ks-audi-r8-lms" to CarSubtitle(570, "3,5s · 1250 Kg · ~ R$: 500.000–900.000"),
        "assetto-ks-audi-tt-vln" to CarSubtitle(390, "3,5s · 54 Kgfm · 1120 Kg · ~ R$: 100.000–500.000"),
        "assetto-ks-bmw-m235i-racing" to CarSubtitle(333, "4,8s · 51 Kgfm · 1424 Kg"),
        "assetto-ks-bmw-m4-akrapovic" to CarSubtitle(445, "3,9s · 60 Kgfm · 1572 Kg · ~ R$: 300.000–700.000"),
        "assetto-ks-corvette-c7r" to CarSubtitle(495, "3,3s · 1320 Kg · ~ R$: 300.000–700.000"),
        "assetto-ks-ferrari-812-superfast" to CarSubtitle(800, "2,9s · 73 Kgfm · 1525 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-ks-ferrari-f138" to CarSubtitle(763, "2,4s · 32 Kgfm · 642 Kg"),
        "assetto-ks-ferrari-f2004" to CarSubtitle(865, "2,4s"),
        "assetto-ks-ferrari-sf15t" to CarSubtitle(840, "2,4s · 74 Kgfm · 702 Kg"),
        "assetto-ks-ferrari-sf70h" to CarSubtitle(null, "2,4s"),
        "assetto-ks-ford-mustang-2015" to CarSubtitle(435, "4,4s · 55 Kgfm · 1680 Kg · ~ R$: 250.000–600.000"),
        "assetto-ks-glickenhaus-scg003" to CarSubtitle(530, "3,3s · 71 Kgfm · 1350 Kg · ~ R$: 100.000–500.000"),
        "assetto-ks-lamborghini-gallardo-sl-s3" to CarSubtitle(1200, "2,5s · 1390 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-ks-lamborghini-huracan-gt3" to CarSubtitle(600, "3,3s · 1239 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-ks-lamborghini-sesto-elemento" to CarSubtitle(570, "2,5s · 55 Kgfm · 999 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-ks-maserati-alfieri" to CarSubtitle(460, "4,5s · 53 Kgfm · 1496 Kg · ~ R$: 250.000–900.000"),
        "assetto-ks-maserati-gt-mc-gt4" to CarSubtitle(430, "3,3s · 55 Kgfm · 1410 Kg"),
        "assetto-ks-maserati-levante" to CarSubtitle(424, "5s · 59 Kgfm · 2108 Kg · ~ R$: 250.000–900.000"),
        "assetto-ks-maserati-mc12-gt1" to CarSubtitle(580, "3,1s · 66 Kgfm · 1100 Kg · ~ R$: 250.000–900.000"),
        "assetto-ks-maserati-quattroporte" to CarSubtitle(530, "4,7s · 72 Kgfm · 1900 Kg · ~ R$: 250.000–900.000"),
        "assetto-ks-mazda-787b" to CarSubtitle(690, "2,9s · 62 Kgfm · 845 Kg · ~ R$: 100.000–300.000"),
        "assetto-ks-mazda-miata" to CarSubtitle(130, "8,8s · 15 Kgfm · 1040 Kg · ~ R$: 100.000–300.000"),
        "assetto-ks-mazda-rx7-spirit-r" to CarSubtitle(276, "5,3s · 32 Kgfm · 1270 Kg · ~ R$: 100.000–300.000"),
        "assetto-ks-mazda-rx7-tuned" to CarSubtitle(444, "3,8s · 41 Kgfm · 1312 Kg · ~ R$: 100.000–300.000"),
        "assetto-ks-mclaren-570s" to CarSubtitle(562, "3,2s · 61 Kgfm · 1313 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-ks-mclaren-650-gt3" to CarSubtitle(500, "3,3s · 51 Kgfm · 1240 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-ks-mclaren-f1-gtr" to CarSubtitle(595, "2,6s · 71 Kgfm · 1010 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-ks-mclaren-p1" to CarSubtitle(903, "2,8s · 92 Kgfm · 1450 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-ks-mclaren-p1-gtr" to CarSubtitle(986, "2,4s · 1400 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-ks-mercedes-190-evo2" to CarSubtitle(370, "4,7s · 32 Kgfm · 980 Kg"),
        "assetto-ks-mercedes-c9" to CarSubtitle(750, "2,9s · 51 Kgfm · 905 Kg · ~ R$: 100.000–500.000"),
        "assetto-ks-nissan-gtr-gt3" to CarSubtitle(600, "3,3s · 71 Kgfm · 1300 Kg · ~ R$: 500.000–900.000"),
        "assetto-ks-pagani-huayra-bc" to CarSubtitle(740, "2,8s · 112 Kgfm · 1218 Kg · ~ R$: 8.000.000"),
        "assetto-ks-porsche-718-boxster-s" to CarSubtitle(350, "4,6s · 43 Kgfm · 1355 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-ks-porsche-718-boxster-s-pdk" to CarSubtitle(350, "4,2s · 43 Kgfm · 1385 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-ks-porsche-718-cayman-s" to CarSubtitle(350, "4,7s · 43 Kgfm · 1355 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-ks-porsche-718-spyder-rs" to CarSubtitle(150, "4,1s · 15 Kgfm · 580 Kg"),
        "assetto-ks-porsche-911-gt3-cup-2017" to CarSubtitle(485, "3,3s · 1220 Kg"),
        "assetto-ks-porsche-911-gt3-r-2016" to CarSubtitle(500, "3,3s · 1245 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-ks-porsche-911-r" to CarSubtitle(500, "3,8s · 47 Kgfm · 1370 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-ks-porsche-911-rsr-2017" to CarSubtitle(510, "3,5s · 1245 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-ks-porsche-917-k" to CarSubtitle(600, "6,8s · 820 Kg"),
        "assetto-ks-porsche-918-spyder" to CarSubtitle(887, "2,6s · 130 Kgfm · 1640 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-ks-porsche-919-hybrid-2015" to CarSubtitle(900, "2,2s · 875 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-ks-porsche-919-hybrid-2016" to CarSubtitle(900, "2,2s · 875 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-ks-porsche-991-carrera-s" to CarSubtitle(420, "3,9s · 51 Kgfm · 1515 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-ks-porsche-cayenne" to CarSubtitle(570, "4,1s · 82 Kgfm · 2235 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-ks-porsche-cayman-gt4-clubsport" to CarSubtitle(385, "3,3s · 43 Kgfm · 1300 Kg"),
        "assetto-ks-porsche-cayman-gt4-std" to CarSubtitle(385, "4,4s · 43 Kgfm · 1340 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-ks-porsche-macan" to CarSubtitle(400, "4,8s · 56 Kgfm · 1925 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-ks-porsche-panamera" to CarSubtitle(550, "3,6s · 79 Kgfm · 2070 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-ks-praga-r1" to CarSubtitle(210, "3,5s · 22 Kgfm · 585 Kg"),
        "assetto-ks-ruf-rt12r-awd" to CarSubtitle(730, "3,4s · 96 Kgfm · 1 Kg · ~ R$: 250.000–900.000"),
        "assetto-ks-toyota-ae86" to CarSubtitle(122, "9,2s · 14 Kgfm · 925 Kg · ~ R$: 100.000–500.000"),
        "assetto-ks-toyota-ae86-drift" to CarSubtitle(185, "4,2s · 21 Kgfm · 920 Kg · ~ R$: 100.000–500.000"),
        "assetto-ks-toyota-celica-st185" to CarSubtitle(295, "5,5s · 47 Kgfm · 1045 Kg"),
        "assetto-ks-toyota-gt86" to CarSubtitle(200, "7,6s · 21 Kgfm · 1250 Kg · ~ R$: 250.000–600.000"),
        "assetto-ks-toyota-supra-mkiv-drift" to CarSubtitle(624, "4,2s · 77 Kgfm · 1505 Kg · ~ R$: 250.000–600.000"),
        "assetto-ks-toyota-supra-mkiv-tuned" to CarSubtitle(690, "4,2s · 77 Kgfm · 1505 Kg · ~ R$: 250.000–600.000"),
        "assetto-ks-toyota-ts040" to CarSubtitle(1000, "2,9s · ~ R$: 100.000–500.000"),
        "assetto-ktm-xbow-r" to CarSubtitle(300, "3,7s · 41 Kgfm · 795 Kg · ~ R$: 250.000–900.000"),
        "assetto-lamborghini-aventador-sv" to CarSubtitle(750, "2,8s · 70 Kgfm · 1525 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-lamborghini-gallardo-sl" to CarSubtitle(570, "3,4s · 55 Kgfm · 1340 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-lamborghini-huracan-performante" to CarSubtitle(640, "2,9s · 61 Kgfm · 1382 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-lamborghini-huracan-st" to CarSubtitle(620, "3,2s · 58 Kgfm · 1270 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-lotus-evora-gte-carbon" to CarSubtitle(420, "4,4s · 47 Kgfm · 1285 Kg · ~ R$: 250.000–900.000"),
        "assetto-lotus-evora-gx" to CarSubtitle(440, "4,5s · 47 Kgfm · 1395 Kg"),
        "assetto-mclaren-mp412c" to CarSubtitle(616, "3,2s · 61 Kgfm · 1434 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-mclaren-mp412c-gt3" to CarSubtitle(500, "3,3s · 51 Kgfm · 1245 Kg · ~ R$: 2.000.000–4.000.000"),
        "assetto-mercedes-amg-gt3" to CarSubtitle(520, "3,3s · 61 Kgfm · 1265 Kg · ~ R$: 100.000–500.000"),
        "assetto-mercedes-sls" to CarSubtitle(571, "3,8s · 66 Kgfm · 1620 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-mercedes-sls-gt3" to CarSubtitle(520, "3,3s · 61 Kgfm · 1265 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-nissan-370z" to CarSubtitle(350, "5s · 38 Kgfm · 1498 Kg · ~ R$: 100.000–500.000"),
        "assetto-nissan-gtr" to CarSubtitle(592, "2,1s · 66 Kgfm · 1750 Kg · ~ R$: 500.000–900.000"),
        "assetto-nissan-skyline-r34" to CarSubtitle(325, "4,9s · 40 Kgfm · 1560 Kg · ~ R$: 500.000–900.000"),
        "assetto-p4-5-2011" to CarSubtitle(450, "3,9s · 51 Kgfm · 1230 Kg · ~ R$: 100.000–500.000"),
        "assetto-pagani-huayra" to CarSubtitle(730, "2,7s · 102 Kgfm · 1360 Kg · ~ R$: 8.000.000"),
        "assetto-pagani-zonda-r" to CarSubtitle(750, "2,7s · 72 Kgfm · 1070 Kg · ~ R$: 8.000.000"),
        "assetto-porsche-911-gt3-rs" to CarSubtitle(500, "3,1s · 47 Kgfm · 1420 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-porsche-991-turbo-s" to CarSubtitle(580, "2,9s · 76 Kgfm · 1600 Kg · ~ R$: 700.000–2.000.000"),
        "assetto-tatuusfa1" to CarSubtitle(198, "2,6s · 23 Kgfm · 455 Kg"),
        "assetto-toyota-supra-mkiv" to CarSubtitle(280, "5s · 47 Kgfm · 1510 Kg · ~ R$: 250.000–600.000"),
        "modded-aston-martin-dbrs9-gt3" to CarSubtitle(620, "3,3s · 71 Kgfm · 1370 Kg"),
        "modded-audi-r8-lms-gt2" to CarSubtitle(569, "3,3s · 58 Kgfm · 1350 Kg"),
        "modded-audi-tt-cup-2015" to CarSubtitle(310, "5s · 42 Kgfm · 1125 Kg"),
        "modded-bmw-m8-gtlm" to CarSubtitle(500, "3,3s · 1250 Kg"),
        "modded-bugatti-chiron-pur-sport" to CarSubtitle(1500, "2,3s · 163 Kgfm · 1995 Kg"),
        "modded-cadillac-escalade-esv" to CarSubtitle(403, "6,8s · 58 Kgfm · 2235 Kg"),
        "modded-chevrolet-camaro-concept" to CarSubtitle(400, "5,4s · 56 Kgfm · 1535 Kg"),
        "modded-chevrolet-corvette-c6-z06-stanced" to CarSubtitle(505, "4,2s · 65 Kgfm · 1420 Kg"),
        "modded-chevrolet-corvette-c7-stingray-hellspec" to CarSubtitle(null, "3,8s · 103 Kgfm · 1496 Kg"),
        "modded-ferrari-360-challenge-stradale" to CarSubtitle(null, "4s · 38 Kgfm · 1280 Kg"),
        "modded-ferrari-458-italia-gte-ferruccio" to CarSubtitle(465, "3,4s · 46 Kgfm · 1245 Kg"),
        "modded-ferrari-458-italia-tune" to CarSubtitle(574, "3,8s · 55 Kgfm · 1140 Kg"),
        "modded-ferrari-488-gte-evo-michelotto" to CarSubtitle(583, "3,3s · 82 Kgfm · 1270 Kg"),
        "modded-ferrari-f1-2000" to CarSubtitle(null, "2,6s · 36 Kgfm · 535 Kg"),
        "modded-ferrari-f430-gt2-2007" to CarSubtitle(550, "3,3s · 50 Kgfm · 1100 Kg"),
        "modded-ferrari-laferrari-trio" to CarSubtitle(805, "3s · 89 Kgfm · 1480 Kg"),
        "modded-ferrari-sf90-xx-stradale-2024" to CarSubtitle(1030, "2,2s · 82 Kgfm · 1560 Kg"),
        "modded-lamborghini-aventador-sv" to CarSubtitle(750, "2,8s · 70 Kgfm · 1525 Kg"),
        "modded-lamborghini-huracan-trofeo-evo2" to CarSubtitle(700, "3,1s · 71 Kgfm · 1376 Kg"),
        "modded-lexus-lfa" to CarSubtitle(552, "3,7s · 49 Kgfm · 1480 Kg"),
        "modded-lexus-lfa-concept-gt500" to CarSubtitle(507, "3,6s · 46 Kgfm · 1025 Kg"),
        "modded-lexus-lfa-no-hesi-spec" to CarSubtitle(858, "3,8s · 75 Kgfm · 1562 Kg"),
        "modded-lexus-lfa-nurburgring-edition" to CarSubtitle(552, "3,7s · 49 Kgfm · 1562 Kg"),
        "modded-mercedes-amg-project-one-hypercar" to CarSubtitle(760, "2,5s · 1300 Kg"),
        "modded-mercedes-benz-amg-gt3-evo-2020-sprint" to CarSubtitle(520, "3,3s · 61 Kgfm · 1265 Kg"),
        "modded-mitsubishi-eclipse-gsx-r" to CarSubtitle(null, "5,9s · 60 Kgfm · 1100 Kg"),
        "modded-mitsubishi-lancer-evolution-viii-gsr" to CarSubtitle(305, "5,9s · 39 Kgfm · 1400 Kg"),
        "modded-nissan-350z" to CarSubtitle(301, "5,8s · 42 Kgfm · 1510 Kg"),
        "modded-nissan-370z-widebody" to CarSubtitle(1017, "4,2s · 123 Kgfm · 1500 Kg"),
        "modded-nissan-gt-r-nismo-godzilla" to CarSubtitle(831, "2,1s · 101 Kgfm · 1700 Kg"),
        "modded-porsche-911-992-turbo-s-pdk" to CarSubtitle(968, "2,4s · 121 Kgfm · 1640 Kg"),
        "modded-porsche-911-gt3-rs-hellspec" to CarSubtitle(null, "3,1s · 66 Kgfm · 1395 Kg"),
        "modded-porsche-911-turbo-s" to CarSubtitle(640, "2,7s · 77 Kgfm · 1850 Kg"),
        "modded-porsche-carrera-gt-rs" to CarSubtitle(681, "3,5s · 65 Kgfm · 1340 Kg"),
        "modded-toyota-supra-wangan" to CarSubtitle(648, "3,8s · 71 Kgfm · 1432 Kg"),
    )

    private val catalogMinHorsepower: Int by lazy {
        subtitles.values.mapNotNull { it.horsepower }.min()
    }

    /** Catalog max HP (e.g. 1500) is an outlier; cap the red end so the scale stays useful. */
    private const val HORSEPOWER_COLOR_MAX_HP = 1000

    fun forProfileId(profileId: String): CarSubtitle = subtitles[profileId] ?: fallback

    fun horsepowerColor(horsepower: Int): Color {
        val minHorsepower = catalogMinHorsepower
        val maxHorsepower = HORSEPOWER_COLOR_MAX_HP
        val span = (maxHorsepower - minHorsepower).coerceAtLeast(1)
        val fraction = ((horsepower - minHorsepower).toFloat() / span).coerceIn(0f, 1f)

        return lerp(
            Color(0xFF38E58C),
            Color(0xFFFF394F),
            fraction,
        )
    }
}
